---
- name: MOTDに「Hello World!」を表示する
  hosts: AP01
  become: yes
  tasks:
    - copy:
        src: files/motd-hello-world
        dest: /etc/motd
        owner: vagrant
        group: vagrant
        mode: 0644